trigger: none

pool: vihaan_agent_pool
 
steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Environment'
    backendServiceArm: 'Azure subscription 1(712bfb2b-0ea5-4e2e-ae12-b849c506ebe4)'
    backendAzureRmStorageAccountName: 'mystoagedabba'
    backendAzureRmContainerName: 'mycontainerdabba'
    backendAzureRmKey: 'mystate.tfstate'